Add Form credentials
huysentruitw/oauth2-client-handler pull request #3
Opened 2017-04-12 21:54 UTC by mrinaldi

Some servers do not support basic authentication credentials.
Therefore, create an option to specify whether basic authentication or
form credentials should be sent.

2017-04-13 04:56 UTC, huysentruitw requested changes

2017-04-13 04:56 UTC, huysentruitw commented on tests/OAuth2ClientHandler.Tests/Helpers/Startup.cs
> +                                 ctx.TryGetFormCredentials(out clientId, out clientSecret)) &&
Can you split this into two if's so bith credential types are tested with different credentials. This way we're sure the correct method is being used.

2017-04-13 04:56 UTC, huysentruitw commented on tests/OAuth2ClientHandler.Tests/AuthorizerTests.cs
> +
Possible to add an other test case with an invalid secret while using the forms credential type?

2017-04-13 14:05 UTC, mrinaldi commented on tests/OAuth2ClientHandler.Tests/Helpers/Startup.cs
> +                                 ctx.TryGetFormCredentials(out clientId, out clientSecret)) &&
I've created another method instead to make the code more clear. Done in 07c5f84.

2017-04-13 14:07 UTC, mrinaldi commented on tests/OAuth2ClientHandler.Tests/AuthorizerTests.cs
> +
I've replicated the tests instead, running all tests for both credential types. Done in 07c5f84.

2017-05-18 07:30 UTC, huysentruitw reviewed
Oops, sorry. I had done a review on the code but I see the review is still in a pending state as I forgot to submit it. All the time, I was waiting for an update on this PR. I have submitted the review now, but I don't know if you're still willing to do the changes. If not, no problem, I'll incorporate this whenever I have the time.

2017-05-18 07:30 UTC, huysentruitw commented on tests/OAuth2ClientHandler.Tests/AuthorizerTests.cs
> -    public class AuthorizerTests
Sorry I have to ask but can you please revert this change to the unit test to your previous version? I don't like the idea of a baseclass in a unit test like this because, why would we use inheritence for the CredentialsType and not for the GrantType f.e. I also only allow base classes in unit tests for adding helpermethods and not for complete test methods.

2017-06-29 14:20 UTC, closed without merging